### ISSUE TITLE
Take a file of domains, output WP sites

### ISSUE THREAD

**Issue by JDiPierro** [IamLizu/wpdetect#2]
Thanks for sharing this! It helped me recon my company's list of domains to find WP sites to further inspect for vulnerabilities.

It'd be awesome if this could take a file with 1 domain per line, run through the domains in the file, and output the list of domains that were detected as WP sites.

**Comment by IamLizu** [comment]
That would be awesome yes, appreciated. I will add it in the next release.

**Comment by IamLizu** [comment]
@JDiPierro, hey, please install the latest version using pip and try now! Cheers!

**Comment by soracyberteam** [comment]
> @JDiPierro, hey, please install the latest version using pip and try now! Cheers!

how to do output?

**Comment by IamLizu** [comment]
> how to do output?
@soracyberteam, First of all, sorry for replying late. I apologize, I am unable to understand your question. What do you want to output? Don't the output shows as you execute in the terminal?
